### ISSUE TITLE
Doesn't play well with HTTP GET when request body is present

### ISSUE THREAD

**Issue by ZitRos** [felixge/httpsnoop#11] opened 2020-09-04 19:10 UTC
Hello! Thanks for writing a good module.

I know no one uses HTTP GET with body in the wild, but indeed it is possible to send GET with the body data. And, from what I accidentally noticed, when your library is plugged to the request, this request errors:

```
2020/09/04 21:52:31 httputil: ReverseProxy read error during body copy: stream error: stream ID 1; PROTOCOL_ERROR
```

Here's what I do:

```go
url, err := url.Parse("https://www.google.com")
proxy := logRequestHandler(httputil.NewSingleHostReverseProxy(url))
```

Try `GET <host>/favicon.ico` with any body and it errors. logRequestHandler is:

```go
func logRequestHandler(h http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		m := httpsnoop.CaptureMetrics(h, w, r)
		log.Println("RESPONSE SIZE: " + strconv.FormatInt(m.Written, 10))
	}
	return http.HandlerFunc(fn)
}
```

The error doesn't happen if I remove "logRequestHandler()". The other part of the program if you're curious to test my setup:

```go
func main() {
	port := ":80"
	http.HandleFunc("/", handler())
	log.Println("Listeting on " + port)
	log.Fatal(http.ListenAndServe(port, nil))
}

func handler() func(http.ResponseWriter, *http.Request) {
	return func(res http.ResponseWriter, req *http.Request) {
		url, err := url.Parse("https://www.google.com")
		if err != nil {
			panic(err)
		}

		// Remove logRequestHandler() and the error will be gone
		proxy := logRequestHandler(httputil.NewSingleHostReverseProxy(url))

		req.URL.Host = url.Host
		req.Host = url.Host
		req.URL.Scheme = url.Scheme
		req.Header.Set("X-Forwarded-Host", url.Host)
		proxy.ServeHTTP(res, req)
	}
}
```

Hope this helps to make this library even better! :)

**Comment by felixge** [comment] 2020-09-13 10:12
Hey, thanks for reporting this, and sorry for the late reply. I'll try to take a closer look and see if this can be fixed.

**Comment by ZitRos** [comment] 2020-09-16 12:00
Thank you!

**Comment by felixge** [comment] 2020-09-19 15:09
@ZitRos I was able to reproduce the problem, however, I also see it happening when removing `logRequestHandler`. In both cases the issue appears to be intermittent.

Either way, as far as I can tell the problem is completely unrelated to httpsnoop.

I'll close this issue for now, but if you think I've made a mistake in my analysis, please let em know.

**Closed by felixge** 2020-09-19 15:09 UTC

**Comment by ZitRos** [comment] 2020-09-19 15:27
By testing it one more time, I didn't encounter the error either. Strange...

Anyway, thanks for testing. Maybe the problem was in the end host I were reaching to.

**Comment by felixge** [comment] 2020-09-19 15:39
@ZitRos I'm able to reproduce the issue given the code example using google.com that you provided. It just requires sending the GET request a couple of times. I was using `curl -XGET -d 'some random data' -v ':8080/favicon.ico'`.
